name: Docker CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      image-name: samply/hitron-catalogue
      push-to: ghcr.io
      build-platforms: linux/amd64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
